//confluence 4 by MDN
s0.initScreen()
const f=(()=>a.fft[0]/100)
const pi=(()=>Math.random(Math.PI))
const t=(()=>time)
const sh=(s,m,k,o)=>(shape(s).rotate(t,1).kaleid(k).kaleid(k).kaleid(k).scale(0.5,0.5).modulate(m,0.1).out(o))
const flt=(i,o)=>(src(i).repeat(t,1).mask(shape(pi)).mult(voronoi(t,t)).kaleid(3).rotate(pi,t).color(pi).scale(f).add(i,0.25).out(o))
const flt1=(i,m,o)=>(src(i).modulate(m).scale(pi).out(o))

sh(3,o1,3,o0)
//flt(o0,o1)
//flt(s0,o2)
//sh(t,o0,f,o2)
//sh(t,o2,2,o3)
//flt1(o3,o0,o3)
flt1(o0,o2,o1)
render(o1)
